# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:

  - script: |
      javac ./src/com/company/Main.java -d $(Build.ArtifactStagingDirectory)
      jar -cvf Hello.war $(Build.ArtifactStagingDirectory)
     
    displayName: 'Build and war'

  - script: |
      cd $(Build.ArtifactStagingDirectory)
      java com.company.Main
    displayName: 'Run Code'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
      ArtifactName: 'www' # output artifact named www
